apiVersion: v1
kind: Service
metadata:
  labels:
    app: stock-ms
  name: {{ .Release.Name }}
  #namespace: helm-k8s
spec:
  ports:
    - name: stock-ms
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: stock-ms
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}